In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
data=pd.read_csv("DS_Data.csv")

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Employee_ID      400 non-null    str
 1   Age              384 non-null    float64
 2   Experience       384 non-null    float64
 3   Education_Years  380 non-null    float64
 4   Projects         390 non-null    float64
 5   Certifications   382 non-null    float64
 6   Coding_Hours     376 non-null    float64
 7   Communication    378 non-null    float64
 8   Problem_Solving  385 non-null    float64
 9   Attendance       388 non-null    float64
 10  Internships      385 non-null    float64
 11  Python           378 non-null    float64
 12  SQL              374 non-null    float64
 13  ML               380 non-null    float64
 14  Cloud            387 non-null    float64
 15  Gender           376 non-null    str
 16  Department       382 non-null    str
 17  City             380 non-null    str
 18  Work_Mode        371 non-null    str
 19  Salary           400 non-null    int64
 20  Promotion        400 non-null    int64
dtypes: float64(14), int64(2), str(5)
memory usage: 65.8 KB

In [6]:
data.columns

Index(['Employee_ID', 'Age', 'Experience', 'Education_Years', 'Projects',
       'Certifications', 'Coding_Hours', 'Communication', 'Problem_Solving',
       'Attendance', 'Internships', 'Python', 'SQL', 'ML', 'Cloud', 'Gender',
       'Department', 'City', 'Work_Mode', 'Salary', 'Promotion'],
      dtype='str')

In [7]:
data.isnull().sum()

Employee_ID         0
Age                16
Experience         16
Education_Years    20
Projects           10
Certifications     18
Coding_Hours       24
Communication      22
Problem_Solving    15
Attendance         12
Internships        15
Python             22
SQL                26
ML                 20
Cloud              13
Gender             24
Department         18
City               20
Work_Mode          29
Salary              0
Promotion           0
dtype: int64

In [10]:
data.sample()

,Employee_ID,Age,Experience,Education_Years,Projects,Certifications,Coding_Hours,Communication,Problem_Solving,Attendance,...,Python,SQL,ML,Cloud,Gender,Department,City,Work_Mode,Salary,Promotion
153,EMP2982,45.0,12.0,20.0,27.0,2.0,43.0,57.0,NaN,92.5,...,3.0,6.0,10.0,1.0,Female,BI,Delhi,Hybrid,138423,1

In [11]:
data=data.drop(["Age","City"], axis=1)

In [12]:
data.sample()

,Employee_ID,Experience,Education_Years,Projects,Certifications,Coding_Hours,Communication,Problem_Solving,Attendance,Internships,Python,SQL,ML,Cloud,Gender,Department,Work_Mode,Salary,Promotion
387,EMP4912,12.0,18.0,NaN,6.0,28.0,50.0,77.0,93.7,5.0,3.0,3.0,6.0,3.0,Male,AI,Remote,113349,1

In [13]:
num=[]
cat=[]
for i in data.columns:
    if data[i].dtype=="str":
        cat.append(i)
    else:
        num.append(i)
print("num",num)
print("cat",cat)

num ['Experience', 'Education_Years', 'Projects', 'Certifications', 'Coding_Hours', 'Communication', 'Problem_Solving', 'Attendance', 'Internships', 'Python', 'SQL', 'ML', 'Cloud', 'Salary', 'Promotion']
cat ['Employee_ID', 'Gender', 'Department', 'Work_Mode']

In [14]:
data[num].isnull().sum()

Experience         16
Education_Years    20
Projects           10
Certifications     18
Coding_Hours       24
Communication      22
Problem_Solving    15
Attendance         12
Internships        15
Python             22
SQL                26
ML                 20
Cloud              13
Salary              0
Promotion           0
dtype: int64

In [18]:
num_cols=['Experience', 'Education_Years', 'Projects', 'Certifications', 'Coding_Hours', 'Communication', 'Problem_Solving', 'Attendance', 'Internships', 'Python', 'SQL', 'ML', 'Cloud']
data[num_cols]=data[num_cols].fillna(data[num_cols].mean())

In [19]:
data[num].isnull().sum()

Experience         0
Education_Years    0
Projects           0
Certifications     0
Coding_Hours       0
Communication      0
Problem_Solving    0
Attendance         0
Internships        0
Python             0
SQL                0
ML                 0
Cloud              0
Salary             0
Promotion          0
dtype: int64

In [20]:
data.sample()

,Employee_ID,Experience,Education_Years,Projects,Certifications,Coding_Hours,Communication,Problem_Solving,Attendance,Internships,Python,SQL,ML,Cloud,Gender,Department,Work_Mode,Salary,Promotion
193,EMP8836,8.0,16.021053,16.0,8.0,32.0,80.0,93.0,77.4,2.0,9.0,3.0,6.0,6.0,Female,Analytics,NaN,99250,1

In [21]:
data[cat].isnull().sum()

Employee_ID     0
Gender         24
Department     18
Work_Mode      29
dtype: int64

In [45]:
cat_cols=['Employee_ID', 'Gender', 'Department', 'Work_Mode']
data[cat_cols]=data[cat_cols].fillna(data[cat_cols].mode())

In [53]:
data['Department'].mode()
data['Department']=data['Department'].fillna("AI")

data['Work_Mode'].mode()
data['Work_Mode']=data['Work_Mode'].fillna("Hybrid")

In [54]:
data[cat].isnull().sum()

Employee_ID    0
Gender         0
Department     0
Work_Mode      0
dtype: int64

In [55]:
data.sample()

,Employee_ID,Experience,Education_Years,Projects,Certifications,Coding_Hours,Communication,Problem_Solving,Attendance,Internships,Python,SQL,ML,Cloud,Gender,Department,Work_Mode,Salary,Promotion
221,EMP1453,20.0,17.0,27.0,3.0,26.0,53.0,71.0,85.6,1.0,5.0,2.0,4.0,10.0,Female,Data Science,Office,151666,1

In [56]:
data.isnull().sum()

Employee_ID        0
Experience         0
Education_Years    0
Projects           0
Certifications     0
Coding_Hours       0
Communication      0
Problem_Solving    0
Attendance         0
Internships        0
Python             0
SQL                0
ML                 0
Cloud              0
Gender             0
Department         0
Work_Mode          0
Salary             0
Promotion          0
dtype: int64